# Generated by Django 5.2.11 on 2026-02-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_default_categories(apps, schema_editor):
    Category = apps.get_model("api", "Category")

    defaults = (
        {"name": "Random Thoughts", "color": "#EF9C66", "is_default": True},
        {"name": "School", "color": "#FCDC94", "is_default": True},
        {"name": "Personal", "color": "#78ABA8", "is_default": True},
    )

    for item in defaults:
        Category.objects.update_or_create(
            owner=None,
            name=item["name"],
            defaults={
                "color": item["color"],
                "is_default": item["is_default"],
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.RemoveConstraint(
            model_name="category",
            name="unique_category_name",
        ),
        migrations.AddField(
            model_name="category",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(max_length=7),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", True)),
                fields=("name",),
                name="unique_shared_category_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", False)),
                fields=("owner", "name"),
                name="unique_user_category_name",
            ),
        ),
        migrations.RunPython(
            seed_default_categories,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
